### ISSUE TITLE
{"error":"model  not found in the configuration"}%

### ISSUE THREAD

**Issue by caicongyang** [fruitbars/simple-one-api#22]
cozecn 在config中models 配置了botid , 还是提示model not found ; 

还有哪些要注意的吗 ？ 

`{
  "server_port": ":9191",
  "load_balancing": "random",
  "services": {
    "cozecn": [
      {
        "models": ["7379xxxxxx55182336"],
        "enabled": true,
        "credentials": {
          "token": "pat_ghPyAWD8UkwvD9TLxxxxxxx-xxxxxdMhn4M4vxchGXxMMo"
        },
        "server_url": "https://api.coze.cn/open_api/v2/chat"
      }
    ]
  }
}`

**Comment by fruitbars** [comment]
coze.cn申请使用流程：

https://github.com/fruitbars/simple-one-api/blob/main/docs/coze.cn%E7%94%B3%E8%AF%B7API%E4%BD%BF%E7%94%A8%E6%B5%81%E7%A8%8B.md

**Comment by caicongyang** [comment]
大佬，curl --location --request POST 'http://127.0.0.1:9191/v1/chat/completions' \
--header 'Authorization: Bearer pat_ghPyAWD8UkwvD9TLpIsSXx5MBEtrNdDQoOSdia4gq2haPfy6Mhn4M4vxchGXxMMo' \
--header 'Content-Type: application/json' \
--header 'Accept: */*' \
--header 'Connection: keep-alive' \
--data '{
    "model" : "73794xxxx18855182336", 
    "user": "123333333",
    "query": "收货单的使用场景",
    "stream":false
}'


不会讲model 参数变成 cozecn 需要的botid

**Comment by fruitbars** [comment]
你这里发送到消息不是标准的 openai API消息格式

**Comment by caicongyang** [comment]
感谢大佬支持
