### ISSUE TITLE
[bug]Xunfei spark-lite user content is empty

### ISSUE THREAD

**Issue by zqr10159** [fruitbars/simple-one-api#23]
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/4e3069e9-247e-4bd5-bd2b-c6a46b699fa1)
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/68a30ffb-a287-49fb-ae76-f4e7c0715282)
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/78bc2dff-91b9-45d2-b498-45e16355c38d)
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/c57202c3-d148-4b64-a133-182c70bbded5)
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/c147b044-110d-47fb-a1ec-c3f167f010bf)

**Comment by fruitbars** [comment]
错误表示 content内容为空，也就是你发的空消息
<img width="788" alt="image" src="https://github.com/fruitbars/simple-one-api/assets/1823364/3a44174a-4918-4546-a4aa-a9f937485218">

**Comment by zqr10159** [comment]
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/2a5bc24f-30d0-4afc-a636-65de5c6228e1)请问一下这个text不是我发送的嘛，我是根据springai的文档发送的消息，代码在issue中

**Comment by fruitbars** [comment]
openai api标准消息格式：

参考文档：https://platform.openai.com/docs/api-reference/chat/create

curl https://api.openai.com/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
    "model": "gpt-4o",
    "messages": [
      {
        "role": "system",
        "content": "You are a helpful assistant."
      },
      {
        "role": "user",
        "content": "Hello!"
      }
    ]
  }'

**Comment by zqr10159** [comment]
好的，感谢，我再试试

**Comment by zqr10159** [comment]
你好，我看了一下springai的请求、openai文档和项目源码，可能是因为default模式下，只有content字段导致的
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/eafe53f3-98b9-49dc-a34a-438703688e34)
，实际上，springai会发送完整的输入类型，就像文档中的input image一样
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/215fbb7e-0bf4-4103-a930-c860affa260d)
![image](https://github.com/fruitbars/simple-one-api/assets/30048352/99ebd0fb-a516-4924-8a14-d0a65c63c019)
springai对于纯文本的类型，也会带有text，所以与该项目不兼容
