### ISSUE TITLE
能否让“gpt-3.5-turbo”模型自动映射到“random”？

### ISSUE THREAD

**Issue by lololowe** [fruitbars/simple-one-api#25]
有些客户端不支持自定义模型名，那么是否可以让服务端将客户端请求的默认模型“gpt-3.5-turbo”转换为“random”或某个具体模型？

**Comment by fruitbars** [comment]
有个设置model_redirect，即模型重定向，可以将客户端传过来的模型名称，重定向到另一个模型名称

参考文档：https://github.com/fruitbars/simple-one-api/blob/main/docs/config.json%E8%AF%A6%E7%BB%86%E8%AF%B4%E6%98%8E.md

**Comment by fruitbars** [comment]
v0.9.0以上版本已经支持了
