### ISSUE TITLE
智谱清言报错

### ISSUE THREAD

**Issue by ywxhqwq** [fruitbars/simple-one-api#30]
使用glm-4-0520，glm-4-flash、glm-4-air会报错
` "error": "ChatCompletionStream error: error, status code: 400, message: API 调用参数有误，请检查文档。"`
![e6998073-4124-482e-bf6a-bc5ff6070919](https://github.com/fruitbars/simple-one-api/assets/73981888/f2195b28-f667-48e3-8861-fa32829f9dad)
---
使用glm-4-alltools、glm-4v正常
![批注 2024-06-27 211927](https://github.com/fruitbars/simple-one-api/assets/73981888/c2de1428-da7c-4c90-a48e-b3d0dfd8b3f3)
---
另外glm-4v输入图片会报错
`"error": "ChatCompletionStream error: error, status code: 400, message: 图片输入格式/解析错误"`
![批注 2024-06-27 212105](https://github.com/fruitbars/simple-one-api/assets/73981888/b6ed5e68-681f-4b81-a026-f168a3d5d22e)
---
charglm-3这个模型则会提示 empty response from server
![批注 2024-06-27 212638](https://github.com/fruitbars/simple-one-api/assets/73981888/068a0d8e-165a-4fe8-a823-794155f960d4)
---
我的相关配置文件如图
![20240627213356](https://github.com/fruitbars/simple-one-api/assets/73981888/a49f3c04-f682-433f-abec-51ffca8a9947)
我所使用的simple-one-api为Releases的最新版，客户端使用的是ChatGPT-Next-Web
---

**Comment by fruitbars** [comment]
ChatGPT-Next-Web 默认的top好像是1，glm系列的参数是：

top_p取值说明
> 用温度取样的另一种方法，称为核取样
  取值范围是：(0.0, 1.0) 开区间，不能等于 0 或 1，默认值为 0.7
  模型考虑具有 top_p 概率质量 tokens 的结果
  例如：0.1 意味着模型解码器只考虑从前 10% 的概率的候选集中取 tokens
  建议您根据应用场景调整 top_p 或 temperature 参数，但不要同时调整两个参数


但是设置为1 ，glm-4v能正常返回，而glm-4等其他系列不可以。

目前可以通过设置ChatGPT-Next-Web到小于1试试

**Comment by ywxhqwq** [comment]
> ChatGPT-Next-Web 默认的top类似是1，glm系列的参数是：
> 
> top_p取值说明
> 
> > 用温度取样的另一种方法，称为核取样
> > 取值范围是：(0.0, 1.0) 开区间，不能等于 0 或 1，默认值为 0.7
> > 模型考虑具有 top_p 概率质量 token 的结果
> > 例如：0.1 这意味着模型存储库只考虑从前 10% 的概率候选集中取样 token 并
> > 根据应用场景调整 top_p 或temperature 参数，但不要同时调整两个参数
> 
> 但是设置为1，glm-4v能正常返回，而glm-4等其他系列不可以。
> 
> 目前可以通过设置ChatGPT-Next-Web到小于1试试

试了一下top_p改到1以下确实可以正常使用，但是4v还是不能发图片，不知道是不是ChatGPT-Next-Web的问题，另外charglm-3这个模型依旧提示empty response from server

**Comment by fruitbars** [comment]
因为智谱的图片和openai的图片格式有差异，这周更新版本v0.9，抹平差异

**Comment by fruitbars** [comment]
> > ChatGPT-Next-Web 默认的top类似是1，glm系列的参数是：
> > top_p取值说明
> > > 用温度取样的另一种方法，称为核取样
> > > 取值范围是：(0.0, 1.0) 开区间，不能等于 0 或 1，默认值为 0.7
> > > 模型考虑具有 top_p 概率质量 token 的结果
> > > 例如：0.1 这意味着模型存储库只考虑从前 10% 的概率候选集中取样 token 并
> > > 根据应用场景调整 top_p 或temperature 参数，但不要同时调整两个参数
> > 
> > 
> > 但是设置为1，glm-4v能正常返回，而glm-4等其他系列不可以。
> > 目前可以通过设置ChatGPT-Next-Web到小于1试试
> 
> 试了一下top_p改到1以下确实可以正常使用，但是4v还是不能发图片，不知道是不是ChatGPT-Next-Web的问题，另外charglm-3这个模型依旧提示empty response from server

新版本v0.9.0发布了，可以试试
