### ISSUE TITLE
希望也可以为每个模型单独指定代理

### ISSUE THREAD

**Issue by snaigle** [fruitbars/simple-one-api#31]
当同时使用gemini和 coze时，全局代理不是很合适，
希望能为每个模型可以单独指定代理

另外的问题，在wsl环境下通过配制文件指定代理后访问gemini依然不可用，建议将代理配制在httpclient上 ，不要指定环境变量

**Comment by fruitbars** [comment]
正在实现这块内容，期待下新版0.9.0

**Comment by snaigle** [comment]
如果可以直接在httpclient上设置代理，其实就不需要单独配制http_proxy或https_proxy, 
可以按httpclient的 proxy url规范保留一个proxyUrl配制即可

**Comment by fruitbars** [comment]
v0.9.1试试，可以指定某个service是否开启代理
