### ISSUE TITLE
gemini模型适配问题

### ISSUE THREAD

**Issue by snaigle** [fruitbars/simple-one-api#32]
gemini resp里每个片段都有``` "finishReason": "STOP" ``` ，导致返回的openai resp里也都有这个字段
在使用openai translator 翻译插件时，当遇到finishReason=stop时会直接报错，无法使用
临时修复方案：不再map gemini的 finishReason字段，翻译插件可以正常work

**Comment by fruitbars** [comment]
更新到了v0.9.0可以试试
