### ISSUE TITLE
是否支持讯飞星火的其他模型，比如4.0ultra

### ISSUE THREAD

**Issue by LYouC** [fruitbars/simple-one-api#34]
我想尝试使用spark的其他模型，但是都显示不支持的模型名字。报错信息如下：
![image](https://github.com/fruitbars/simple-one-api/assets/78360983/26bfcafc-fa2d-4791-8cf0-5de6c1510c72)

我不太清楚是否是模型名称写错了，但是我在官方文档中看到的model名称只有以下几个，尝试了之后发现都失败了
![image](https://github.com/fruitbars/simple-one-api/assets/78360983/1b15c879-a545-4831-a155-e05a7d9bd1b1)

**Comment by fruitbars** [comment]
可以的，预计本周发布新版本v0.9.0
可以提前docker体验[v0.9.0test](https://hub.docker.com/layers/fruitbars/simple-one-api/v0.9.0test/images/sha256-238f7567b9375fe8484492e411846c95373bb2a9d8e0186a354807e803aefc4b?context=repo)

**Comment by fruitbars** [comment]
更新了v0.9.0，可以试试
