### ISSUE TITLE
腾讯混元大模型 也开始限量了

### ISSUE THREAD

**Issue by bequt** [fruitbars/simple-one-api#35]
![image](https://github.com/fruitbars/simple-one-api/assets/16882457/b6004d72-9e02-4252-959e-6a58b5493bff)

**Comment by fruitbars** [comment]
huanyuan-lite这个模型是免费的，有5并发限制，其他的是单独赠送的

**Comment by fruitbars** [comment]
确认得开通后付费，hunyuan-lite才完全免费，但是后付费需要小心风险就是跑其他模型是要计费的。
