### ISSUE TITLE
这个文件名“install_simple_one_api_service.sh ”多了个空格导致无法clone 

### ISSUE THREAD

**Issue by efan006** [fruitbars/simple-one-api#37]
![image](https://github.com/fruitbars/simple-one-api/assets/11324229/ad410177-42b3-4030-87f8-4a0b2841f3ca)

我提交了修复这个问题的PR
https://github.com/fruitbars/simple-one-api/pull/36

**Comment by fruitbars** [comment]
OK，合并了
