### ISSUE TITLE
 windows 哪个版本的 golang 可以编译成功？我的编译为空

### ISSUE THREAD

**Issue by enjoyloveless** [fruitbars/simple-one-api#4]
![image](https://github.com/fruitbars/simple-one-api/assets/33715226/5718f258-3781-47e5-8d27-d6f28485993e)

编译出来空文件夹

**Comment by fruitbars** [comment]
go1.18以上试试呢？
或者用已经编译号的版本：https://github.com/fruitbars/simple-one-api/releases
