### ISSUE TITLE
可否添加FreeBSD支持

### ISSUE THREAD

**Issue by ywxhqwq** [fruitbars/simple-one-api#42]
请问可否添加FreeBSD系统的支持，serv00的免费机子系统是FreeBSD，要是可以部署在那上面就好了

**Comment by fruitbars** [comment]
后续版本可以加上的，
当前如果不在在其他系统上可以在主目录直接这样交叉编译
GOOS=freebsd GOARCH=amd64 go build

**Comment by ywxhqwq** [comment]
> 后续版本可以加上的， 当前如果在其他版本可以在主目录直接这样交叉编译 GOOS=freebsd GOARCH=amd64 go build

感谢，我去试试

**Comment by fruitbars** [comment]
加上了，试试v0.9.2-beta
https://github.com/fruitbars/simple-one-api/releases/tag/v0.9.2-beta
