### ISSUE TITLE
Release 里的 Gin 是 Debug 模式

### ISSUE THREAD

**Issue by yuanyiwei** [fruitbars/simple-one-api#5]
>[GIN-debug] [WARNING] Creating an Engine instance with the Logger and Recovery middleware already attached.
>
>[GIN-debug] [WARNING] Running in "debug" mode. Switch to "release" mode in production.
> - using env:   export GIN_MODE=release
> - using code:  gin.SetMode(gin.ReleaseMode)
>
>[GIN-debug] POST   /v1/chat/completions      --> simple-one-api/pkg/handler.OpenAIHandler (4 handlers)

RT（

**Comment by fruitbars** [comment]
v0.3 修复了，默认为release了
