### ISSUE TITLE
能否将 NormalizeMessages 默认关闭

### ISSUE THREAD

**Issue by rogeryoungh** [fruitbars/simple-one-api#51]
我 debug 了很久，为什么直接调 api 和通过 simple-one-api 调用大模型返回完全不同，最后发现 messages 不是原样发出的，我中间的 prompt 被清理了。。。

我认为保持 messages 原样传递更符合直觉，大部分用户只是想当一个网关吧，不需要改变 message。有过滤 system 角色需求应是少数。

**Comment by fruitbars** [comment]
你的原始消息是什么呢？

**Comment by rogeryoungh** [comment]
我希望在每次回复前增加要求，原始消息如下，然后 system 那条不见了。我使用的是 kimi 的 openai 接口。

```
{'role': 'user', 'content': '你的家乡在哪里'},
{'role': 'system', 'content': '请以“是杭州呀”为开头,接着回答问题'}
```

**Comment by fruitbars** [comment]
system只能存在第一条消息当中哈。NormalizeMessages主要是解决有些客户端传递消息错误（比如system不在第一条）或者消息混乱的情况（多条user prompt而不是user prompt和assitant消息交替的情况）。

不过这块可以做成配置，以满足如果希望直接传递不用做处理的情况。

**Comment by rogeryoungh** [comment]
请问一下 system 为什么只能存在于第一条呢？我找不到要求这个的文档。moonshot 甚至建议 [定期插入 system 以更好的角色扮演](https://platform.moonshot.cn/docs/guide/prompt-best-practice#在请求中要求模型扮演一个角色可以获得更准确的输出)。

**Comment by fruitbars** [comment]
还真的是，moonshot竟然支持中间穿插system，这块我再确认下，看怎么尽量保持各家都兼容

**Comment by fruitbars** [comment]
v0.9.5已经支持了
https://github.com/fruitbars/simple-one-api/releases/tag/v0.9.5
