### ISSUE TITLE
ollama Error reading response body

### ISSUE THREAD

**Issue by ZanebonoAlter** [fruitbars/simple-one-api#52]
![image](https://github.com/user-attachments/assets/9ad245fd-695f-4b75-b92a-1b7e50a5e718)  

注释掉openai_ollama_handler.go中handleResponse的  
defer resp.Body.Close()  
就可以了

**Comment by fruitbars** [comment]
是有点问题，我来修复下，下个版本更新

**Comment by fruitbars** [comment]
v0.9.4修复了，https://github.com/fruitbars/simple-one-api/releases/tag/v0.9.4
