### ISSUE TITLE
希望增加对gpt-4o-mini的视觉问答接口支持

### ISSUE THREAD

**Issue by TdRoseval** [fruitbars/simple-one-api#54]
![image](https://github.com/user-attachments/assets/95e4a4ce-db3f-4ec2-a5f7-61b3c3d26103)

希望增加对gpt-4o-mini、internvl2等更多多模态大模型的支持

**Comment by fruitbars** [comment]
在simple-one-api中已经默认设定了一些模型支持multi content，这些模型主要是支持多模态的模型。例如
"gpt-4o", "gpt-4-turbo", "glm-4v", "gemini-*"
如果需要设置其他的模型，可以这样配置
{
    "multi_content_models":["gpt-4o-mini"]
}
