### ISSUE TITLE
Autogen调用代理后的千帆大模型报错

### ISSUE THREAD

**Issue by jian1621** [fruitbars/simple-one-api#56]
用官方AutogenStudio调用代理后的千帆大模型进行测试时会报'NoneType'错，但是调用aihubmix转发的openAi接口不报错，怀疑是模型名称代理的问题，请求的时候，根据配置将gpt-3.5-turbo转换为ERNIE-Speed-128K发给千帆了，但是消息回来的时候没有将消息体里的ERNIE-Speed-128K转成gpt-3.5-turbo，导致autogen处理不了了。

**Comment by fruitbars** [comment]
v0.9.4修复了，https://github.com/fruitbars/simple-one-api/releases/tag/v0.9.4
