### ISSUE TITLE
请问没有适配模型中的工具功能吗？

### ISSUE THREAD

**Issue by Rabbit-bear** [fruitbars/simple-one-api#58]
看了下库中openai的请求的结构体支持传参工具内容，而响应的结构体不支持传参工具内容

请求
![image](https://github.com/user-attachments/assets/35935cbe-ceeb-4bef-8c43-286d6618d2ab)

响应
![image](https://github.com/user-attachments/assets/4fdebf76-fb22-4828-835c-c6d8071cec54)

**Comment by fruitbars** [comment]
好的，响应结构体这个准备整体做个升级

**Comment by Rabbit-bear** [comment]
> 好的，响应结构体这个准备整体做个升级

请问这个大概需要多久呢？或者我这边来帮忙试着做一下？

**Comment by fruitbars** [comment]
试着推个pr？

**Comment by Rabbit-bear** [comment]
> 试着推个pr？

好的，这周末我推个pr

**Comment by Rabbit-bear** [comment]
#66 已经提交pr哈 @fruitbars
