### ISSUE TITLE
可以添加azure openai 的支持吗

### ISSUE THREAD

**Issue by 1765659645** [fruitbars/simple-one-api#6]

**Comment by fruitbars** [comment]
可以，安排！

**Comment by fruitbars** [comment]
v0.7已经支持可，可以更新版本或者docker体验下

**Comment by 1765659645** [comment]
> v0.7已经支持可，可以更新版本或者docker体验下

有没有azure openai 接入文档

**Comment by 1765659645** [comment]
打包出来的有支持mac的包吗

**Comment by fruitbars** [comment]
v0.8.0 已发布，可以docker更新
或者下载预编译文件：https://github.com/fruitbars/simple-one-api/releases/tag/v0.8
