### ISSUE TITLE
适配文心智能体，APPID和密钥两个参数

### ISSUE THREAD

**Issue by lopins** [fruitbars/simple-one-api#60]
适配文心智能体，APPID和密钥两个参数

**Comment by fruitbars** [comment]
v0.9.5已经支持了
https://github.com/fruitbars/simple-one-api/releases/tag/v0.9.5

**Comment by someonebw** [comment]
适配这个“文心智能体”的conig.json范例文件，能否提供？

**Comment by someonebw** [comment]
自己测试搞定了，留给需要的人吧。
//文心智能体配置。your_agent_id=appid
{
  "debug": false,
  "load_balancing": "random",
  "services": {
    "agentbuilder": [
      {
        "models": ["your_agent_id"],
        "enabled": true,
        "credentials": {
          "secret_key": "xxx"
        }
      }
    ]
  }
}

**Comment by fruitbars** [comment]
厉害了👍
