### ISSUE TITLE
对外API怎么使用，文档中没有找到

### ISSUE THREAD

**Issue by lopins** [fruitbars/simple-one-api#61]
```
from openai import OpenAI

client = OpenAI(
    api_key="apikey",
    base_url="http://127.0.0.1:9090/v1"
)

completion = client.chat.completions.create(
    model="glm-4",
    messages=[
        {"role": "system", "content": "你是一个聪明且富有创造力的小说作家"},
        {"role": "user",
         "content": "请你作为童话故事大王，写一篇短篇童话故事，故事的主题是要永远保持一颗善良的心，要能够激发儿童的学习兴趣和想象力，同时也能够帮助儿童更好地理解和接受故事中所蕴含的道理和价值观。"}
    ],
    top_p=0.7,
    temperature=0.9
)

print(completion.choices[0].message)
```

apikey这个参数？

**Comment by lopins** [comment]
> ```
> from openai import OpenAI
> 
> client = OpenAI(
>     api_key="apikey",
>     base_url="http://127.0.0.1:9090/v1"
> )
> 
> completion = client.chat.completions.create(
>     model="glm-4",
>     messages=[
>         {"role": "system", "content": "你是一个聪明且富有创造力的小说作家"},
>         {"role": "user",
>          "content": "请你作为童话故事大王，写一篇短篇童话故事，故事的主题是要永远保持一颗善良的心，要能够激发儿童的学习兴趣和想象力，同时也能够帮助儿童更好地理解和接受故事中所蕴含的道理和价值观。"}
>     ],
>     top_p=0.7,
>     temperature=0.9
> )
> 
> print(completion.choices[0].message)
> ```
> 
> apikey这个参数？

![image](https://github.com/user-attachments/assets/fd5b62ac-3636-4217-8032-874be43de287)

**Comment by fruitbars** [comment]
支持api_key（单个）和api_keys（多个，并且支持设定可以调用哪些模型）

参考文档《2.7 api_keys和api_key字段详解》

https://rsxlecz746.feishu.cn/wiki/Tr8nwkkvii3DJrkCpjQcmReAndV

**Comment by lopins** [comment]
> 支持api_key（单个）和api_keys（多个，并且支持设定可以调用哪些模型）
> 
> 参考文档《2.7 api_keys和api_key字段详解》
> 
> https://rsxlecz746.feishu.cn/wiki/Tr8nwkkvii3DJrkCpjQcmReAndV

api_key字符串的格式有要求吗，proxy配置和api_keys配置是否支持`"enabled": true` 控制字段：

```
  "proxy": {
    "strategy": "default",
    "type": "http",
    "http_proxy": "http://proxy.example.com:8080",
    "https_proxy": "http://proxy.example.com:8443",
    "socks5_proxy": "",
    "timeout": 30
  },
  "api_keys": [
    {
      "api_key": "key1",
      "supported_models": {
        "service1": ["model1", "model2"],
        "service2": ["*"]
      }
    },
    {
      "api_key": "key2",
      "supported_models": {
        "service1": ["model3"],
        "service3": ["model4", "model5"]
      }
    }
  ],
```

**Comment by fruitbars** [comment]
针对某个api_key的开关目前还没有哈

**Comment by lopins** [comment]
> 针对某个api_key的开关目前还没有哈

好的
