### ISSUE TITLE
Gemini "error":"formatted server URL is invalid"

### ISSUE THREAD

**Issue by xvweirong** [fruitbars/simple-one-api#63]
"server_url":"https://generativelanguage.googleapis.com/v1"
调用报错：ERROR   handler/openai_handler.go:277   formatted server URL is invalid

完整配置文件如下：
{
  "server_port":":3001",
  "debug": false,
  "api_key":"sk-123456",
  "load_balancing": "first",
  "proxy":{
    "type":"http",
    "http_proxy": "http://192.168.10.10:3000",
    "strategy": "default"
  },  
  "services": {
    "openai": [
      {
        "models": ["gpt-4o","gpt-4o-mini","gpt-4"
          ,"gemini-1.5-flash"
          ,"gemini-1.5-pro"
          ,"gemini-1.5-pro-exp-0801"
        ],
        "enabled": true,
        "credentials": {
          "api_key": "xxxx"
        },
        "model_redirect": {
              "gpt-4o": "gemini-1.5-flash",
              "gpt-4": "gemini-1.5-pro",
              "gpt-4o-mini": "gemini-1.5-flash"
            },
        "use_proxy":true,
        "server_url":"https://generativelanguage.googleapis.com/v1"
      }
    ]
  }
}

**Comment by fruitbars** [comment]
gemini的地址，这种形式：https://generativelanguage.googleapis.com/v1beta/models

**Comment by xvweirong** [comment]
> gemini的地址，这种形式：https://generativelanguage.googleapis.com/v1beta/models

试了一下，也报同样的错：ERROR   handler/openai_handler.go:277   formatted server URL is invalid

**Comment by fruitbars** [comment]
gemini的话，是这样接入的，service name应该为gemini才行

```
{
  "server_port": ":9099",
  "log_level": "prod",
  "load_balancing": "random",
  "services": {
    "gemini": [
      {
        "models": ["gemini-1.0-pro", "gemini-1.0-pro-latest", "gemini-pro", "gemini-1.5-pro", "gemini-1.5-pro-latest", "gemini-1.5-flash", "gemini-1.5-flash-latest"],
        "enabled": true,
        "credentials": {
          "api_key": "xxx"
        },
        "limit": {
          "rpm": 15,
          "timeout":120
        }
      }
    ]
  }
}
```

**Comment by xvweirong** [comment]
问题解决，谢谢。
service name应该为gemini。
server_url 可选，如果要指定， 可为 https://generativelanguage.googleapis.com/v1/models  或  https://generativelanguage.googleapis.com/v1beta/models
