### ISSUE TITLE
windows 双击EXE黑框一闪？

### ISSUE THREAD

**Issue by lhj5426** [fruitbars/simple-one-api#69]
RT 就没了  EXE黑框一闪就 没有然后了 是什么问题 ？  
![image](https://github.com/user-attachments/assets/e75dada1-db69-4964-9e99-13028bf6f0eb)

**Comment by fruitbars** [comment]
需要加载配置文件config.json哈

**Comment by lhj5426** [comment]
哦哦哦，不像oneapi那样有个网页前端ui设置啊……哈哈
