### ISSUE TITLE
星火的spark试了但是不能用

### ISSUE THREAD

**Issue by ntsmzt** [fruitbars/simple-one-api#83]
Model: chatResp.Model
Message ID: 647b9af6-15d7-47fa-b2f5-1ae5b34c0415
Result: unexpected data format: {"error":"websocket: bad handshake"}
对话的时候显示这个内容提示。

**Comment by fruitbars** [comment]
我没复显出来这个问题，方便加入qq群交流下吗？

**Comment by fruitbars** [comment]
v0.9.6 
修复支持星火的spark-lite模型的调用（因为官方改了参数，以前是general，现在改成了lite，真的是很随意！）

![7b4fe320229fcb7cab58da5e77747781](https://github.com/user-attachments/assets/d08d2a13-81f8-42e4-8ef0-56750e04a475)
