### ISSUE TITLE
无法使用 deepseek 模型

### ISSUE THREAD

**Issue by zwbao** [fruitbars/simple-one-api#9]
debug 显示报错 `openai_handler.go:85: model deepseek-chat not found in the configuration`

**Comment by fruitbars** [comment]
deepseek的接口是兼容openai，因此这样配置即可


```
{
  "services": {
    "openai": [
      {
        "models": ["deepseek-chat"],
        "enabled": true,
        "credentials": {
          "api_key": "xxx"
        }
      }
    ]
  }
}
```

**Comment by zwbao** [comment]
搞定了，谢谢大佬~

**Comment by fruitbars** [comment]
文档新增了deepseek 接入的详细说明，后续可以参考

[deepseek模型申请使用流程.md](https://github.com/fruitbars/simple-one-api/blob/main/docs/deepseek%E6%A8%A1%E5%9E%8B%E7%94%B3%E8%AF%B7%E4%BD%BF%E7%94%A8%E6%B5%81%E7%A8%8B.md)
